### PR TITLE
Convert GH Wiki to doc/ Pharo documentation

### PR DESCRIPTION
**Pull request by tinchodias**

### CODE REVIEW

**Comment by tinchodias** [comment]
The includes a fix for https://github.com/pharo-graphics/Alexandrie/issues/48

**Comment by Ducasse** [comment]
Cool!

**Comment by tinchodias** [comment]
I did the same for Bloc and Toplo, that had wiki with contents that are worth being accesses from the World Menu, and worth being also versioned together with the code.

**Comment by Ducasse** [comment]
Great
Because we could have the book in the document folder in the future too

**Comment by tinchodias** [comment]
Good. In the Bloc's "Getting Started" doc/ page, I linked to your memory cards tutorial booklet. But the link opens in the web browser... it'd be good to have it directly in the Documentation Browser.

**Pull request merged**
